### ISSUE TITLE
does not seem to work at all 18.04.3 LTS

### ISSUE THREAD

**Issue by CNSKnight** [rickysarraf/apt-offline#96] opened 2019-10-02 22:58 UTC
Fresh effort:
apt-offline v1.8.1
Ubuntu 18.04.3 LTS

`sudo apt-offline set --update --upgrade apt-offline.sig`
[apt-offline.sig.txt](https://github.com/rickysarraf/apt-offline/files/4038902/apt-offline.sig.txt)
[apt-offline-get.log](https://github.com/rickysarraf/apt-offline/files/4038916/apt-offline-get.log)

```
$ sudo apt-offline install apt-packages/ | tee apt-offline-install.log
No changelog available
(Y) Yes. Proceed with installation
(N) No, Abort.
(C) Display changelog
(?) Display this help message.
What would you like to do next:  (y, N, ?)Y
Proceeding with installation
ERROR: I couldn't understand file type us.archive.ubuntu.com_ubuntu_dists_bionic-updates_main_i18n_Translation-en.
ERROR: I couldn't understand file type ruby2.5_2.5.1-1ubuntu1.6_amd64.deb.
ERROR: I couldn't understand file type brave-browser-apt-beta.s3.brave.com_dists_bionic_main_binary-amd64_Packages.
ERROR: I couldn't understand file type us.archive.ubuntu.com_ubuntu_dists_bionic-security_multiverse_binary-amd64_Packages.
ERROR: I couldn't understand file type us.archive.ubuntu.com_ubuntu_dists_bionic-updates_universe_binary-i386_Packages.
ERROR: I couldn't understand file type us.archive.ubuntu.com_ubuntu_dists_bionic_multiverse_dep11_Components-amd64.yml.
ERROR: I couldn't understand file type us.archive.ubuntu.com_ubuntu_dists_bionic-updates_main_binary-i386_Packages.
ERROR: I couldn't understand file type linux-firmware_1.173.14_all.deb.
ERROR: I couldn't understand file type us.archive.ubuntu.com_ubuntu_dists_bionic-backports_Release.gpg.
ERROR: I couldn't understand file type brave-browser-beta_1.3.85_amd64.deb.
ERROR: I couldn't understand file type archive.canonical.com_ubuntu_dists_bionic_partner_i18n_Translation-en.
ERROR: I couldn't understand file type ppa.launchpad.net_linrunner_tlp_ubuntu_dists_bionic_InRelease.
Traceback (most recent call last):
  File "/usr/bin/apt-offline", line 28, in <module>
    main()
  File "/usr/lib/python3/dist-packages/apt_offline_core/AptOfflineCoreLib.py", line 2211, in main
    args.func(args)
  File "/usr/lib/python3/dist-packages/apt_offline_core/AptOfflineCoreLib.py", line 1904, in installer
    DirInstallPackages(installPath)
  File "/usr/lib/python3/dist-packages/apt_offline_core/AptOfflineCoreLib.py", line 1875, in DirInstallPackages
    InstallerInstance.magic_check_and_uncompress( FullFileName, filename )
  File "/usr/lib/python3/dist-packages/apt_offline_core/AptOfflineCoreLib.py", line 1511, in magic_check_and_uncompress
    retval = self.decompress_the_file(archive_file, temp_filename, "xz")
  File "/usr/lib/python3/dist-packages/apt_offline_core/AptOfflineLib.py", line 475, in decompress_the_file
    if self.TarGzipBZ2_Uncompress( read_from, write_to ) != True:
  File "/usr/lib/python3/dist-packages/apt_offline_core/AptOfflineLib.py", line 385, in TarGzipBZ2_Uncompress
    TargetFileHandle.write( SourceFileHandle.read() )
  File "/usr/lib/python3.6/lzma.py", line 200, in read
    return self._buffer.read(size)
  File "/usr/lib/python3.6/_compression.py", line 103, in read
    data = self._decompressor.decompress(rawblock, size)
_lzma.LZMAError: Corrupt input data
```

**Comment by rickysarraf** [comment] 2019-11-28 14:22
This bug reports does not have much information.

Can you please share the `apt-offline.sig` file along with the console output of what you ran ?
Can you please specify the version of apt-offline you are running ?
Can you please share console output of `get` command ?
Can you please share console output of `install` command ?

**Comment by dandelionred** [comment] 2020-02-29 14:20
@rickysarraf I can reproduce the error. In my case the reason for "I couldn't understand file type" errors is all debs downloaded are zero size.

The demo is based on docker `ubuntu:bionic-20200112` image.

```
$ docker run -it --rm --init ubuntu:bionic-20200112
...
$ apt update
...
18 packages can be upgraded. Run 'apt list --upgradable' to see them.
$ apt install apt-offline -y
...
$ cd /tmp
$ mkdir fetch
$ apt-offline set --upgrade upgrade.sig
Gathering details needed for 'update' operation
$ apt-offline get -d fetch upgrade.sig

Fetching APT Data

Downloading base-files - 58 KiB                                                             
base-files done                                                             
Downloading bsdutils - 58 KiB                                                             
bsdutils done                                                             
Downloading libext2fs2 - 152 KiB                                                             
libext2fs2 done                                                             
Downloading e2fsprogs - 381 KiB                                                             
e2fsprogs done                                                             
Downloading libuuid1 - 19 KiB                                                             
libuuid1 done                                                             
Downloading libblkid1 - 121 KiB                                                             
libblkid1 done                                                             
Downloading libfdisk1 - 160 KiB                                                             
libfdisk1 done                                                             
Downloading libmount1 - 132 KiB                                                             
libmount1 done                                                             
Downloading libsmartcols1 - 81 KiB                                                             
libsmartcols1 done                                                             
Downloading fdisk - 105 KiB                                                             
fdisk done                                                             
Downloading util-linux - 881 KiB                                                             
util-linux done                                                             
Downloading libsystemd0 - 201 KiB                                                             
libsystemd0 done                                                             
Downloading mount - 104 KiB                                                             
mount done                                                             
Downloading libcom-err2 - 8 KiB                                                             
libcom-err2 done                                                             
Downloading libgcrypt20 - 407 KiB                                                             
libgcrypt20 done                                                             
Downloading libss2 - 10 KiB                                                             
libss2 done                                                             
Downloading libudev1 - 54 KiB                                                             
libudev1 done                                                             
Downloading libgnutls30 - 630 KiB                                                             
libgnutls30 done                                                             
 18 /  18 items: [##############################] 100.0% of 3 MiB
Downloaded data to /tmp/fetch
$ ls -l fetch/
total 0
-rw-r--r-- 1 root root 0 Feb 29 13:55 base-files_10.1ubuntu2.8_amd64.deb
-rw-r--r-- 1 root root 0 Feb 29 13:55 bsdutils_1%3a2.31.1-0.4ubuntu3.5_amd64.deb
-rw-r--r-- 1 root root 0 Feb 29 13:55 e2fsprogs_1.44.1-1ubuntu1.3_amd64.deb
-rw-r--r-- 1 root root 0 Feb 29 13:55 fdisk_2.31.1-0.4ubuntu3.5_amd64.deb
-rw-r--r-- 1 root root 0 Feb 29 13:55 libblkid1_2.31.1-0.4ubuntu3.5_amd64.deb
-rw-r--r-- 1 root root 0 Feb 29 13:55 libcom-err2_1.44.1-1ubuntu1.3_amd64.deb
-rw-r--r-- 1 root root 0 Feb 29 13:55 libext2fs2_1.44.1-1ubuntu1.3_amd64.deb
-rw-r--r-- 1 root root 0 Feb 29 13:55 libfdisk1_2.31.1-0.4ubuntu3.5_amd64.deb
-rw-r--r-- 1 root root 0 Feb 29 13:55 libgcrypt20_1.8.1-4ubuntu1.2_amd64.deb
-rw-r--r-- 1 root root 0 Feb 29 13:55 libgnutls30_3.5.18-1ubuntu1.3_amd64.deb
-rw-r--r-- 1 root root 0 Feb 29 13:55 libmount1_2.31.1-0.4ubuntu3.5_amd64.deb
-rw-r--r-- 1 root root 0 Feb 29 13:55 libsmartcols1_2.31.1-0.4ubuntu3.5_amd64.deb
-rw-r--r-- 1 root root 0 Feb 29 13:55 libss2_1.44.1-1ubuntu1.3_amd64.deb
-rw-r--r-- 1 root root 0 Feb 29 13:55 libsystemd0_237-3ubuntu10.39_amd64.deb
-rw-r--r-- 1 root root 0 Feb 29 13:55 libudev1_237-3ubuntu10.39_amd64.deb
-rw-r--r-- 1 root root 0 Feb 29 13:55 libuuid1_2.31.1-0.4ubuntu3.5_amd64.deb
-rw-r--r-- 1 root root 0 Feb 29 13:55 mount_2.31.1-0.4ubuntu3.5_amd64.deb
-rw-r--r-- 1 root root 0 Feb 29 13:55 util-linux_2.31.1-0.4ubuntu3.5_amd64.deb
```

**Comment by rickysarraf** [comment] 2020-03-05 06:41
I am not sure what version ships with Ubuntu 18.04. Nevertheless, please try with the latest apt-offline, version 1.8.2

**Comment by rickysarraf** [comment] 2020-03-05 06:57
With 1.8.2, everything looks fine here:

```
rrs@priyasi:~$ sudo apt-offline set /tmp/upgrade.uris --upgrade --upgrade-type dist-upgrade
Gathering details needed for 'dist-upgrade' operation
12:25 ♒ ॐ  ☺ 😄    
rrs@priyasi:~$ apt-offline get /tmp/upgrade.uris --bundle /tmp/upgrade.zip --proxy-host chutzpah --proxy-port 3142 --threads 5

Fetching APT Data

ERROR: /tmp/upgrade.zip already present.
Remove it first.
12:25 ♒ ॐ   ☹ 😟=> 1  
rrs@priyasi:~$ rm -rf /tmp/upgrade.zip 
12:25 ♒ ॐ  ☺ 😄    
rrs@priyasi:~$ apt-offline get /tmp/upgrade.uris --bundle /tmp/upgrade.zip --proxy-host chutzpah --proxy-port 3142 --threads 5

Fetching APT Data

WARNING: If you are on a slow connection, it is good to
WARNING: limit the number of threads to a low number like 2.
WARNING: Else higher number of threads executed could cause
WARNING: network congestion and timeouts.

Downloading libncurses-dev - 329 KiB                                                             
Downloading libtinfo6 - 326 KiB                                                             
Downloading libncurses6 - 99 KiB                                                             
Downloading libtinfo6 - 327 KiB                                                             
Downloading libncurses6 - 106 KiB                                                             
libncurses6 done                                                             
libncurses6 done                                                             
Downloading ncurses-bin - 412 KiB                                                             
Downloading libncursesw6 - 129 KiB                                                             
libtinfo6 done                                                             
libtinfo6 done                                                             
libncurses-dev done                                                             
libncursesw6 done                                                             
Downloading ncurses-base - 259 KiB                                                             
Downloading libcrypt-dev - 101 KiB                                                             
ncurses-bin done                                                             
Downloading libcrypt1 - 96 KiB                                                             
Downloading libcrypt1 - 83 KiB                                                             
ncurses-base done                                                             
libcrypt-dev done                                                             
libcrypt1 done                                                             
libcrypt1 done                                                             
Downloading libdico2 - 149 KiB                                                             
Downloading dicod - 263 KiB                                                             
Downloading ncurses-term - 485 KiB                                                             
Downloading coinor-libcbc3 - 708 KiB                                                             
libdico2 done                                                             
Downloading libcupsfilters1 - 184 KiB                                                             
Downloading cups-browsed - 200 KiB                                                             
dicod done                                                             
Downloading cups-filters-core-drivers - 254 KiB                                                             
libcupsfilters1 done                                                             
Downloading libfontembed1 - 120 KiB                                                             
cups-browsed done                                                             
Downloading cups-filters - 561 KiB                                                             
ncurses-term done                                                             
Downloading dh-make - 41 KiB                                                             
libfontembed1 done                                                             
cups-filters-core-drivers done                                                             
Downloading libsuitesparseconfig5 - 21 KiB                                                             
coinor-libcbc3 done                                                             
dh-make done                                                             
Downloading libamd2 - 33 KiB                                                             
libsuitesparseconfig5 done                                                             
libamd2 done                                                             
cups-filters done                                                             
Downloading libcamd2 - 35 KiB                                                             
Downloading libccolamd2 - 37 KiB                                                             
Downloading libcolamd2 - 30 KiB                                                             
Downloading libcholmod3 - 316 KiB                                                             
libcamd2 done                                                             
libccolamd2 done                                                             
libcolamd2 done                                                             
Downloading libllvm9 - 14 MiB                                                             
Downloading libllvm9 - 14 MiB                                                             
Downloading libclang1-9 - 6 MiB                                                             
Downloading liblouis-data - 1 MiB                                                             
libcholmod3 done                                                             
Downloading liblouis20 - 88 KiB                                                             
liblouis20 done                                                             
Downloading liblouisutdml-data - 44 KiB                                                             
liblouisutdml-data done                                                             
Downloading liblouisutdml9 - 85 KiB                                                             
liblouisutdml9 done                                                             
Downloading liblouisutdml-bin - 14 KiB                                                             
liblouisutdml-bin done                                                             
Downloading libqt5core5a - 1 MiB                                                             
liblouis-data done                                                             
Downloading libqt5concurrent5 - 63 KiB                                                             
libqt5concurrent5 done                                                             
Downloading libqt5dbus5 - 233 KiB                                                             
libqt5dbus5 done                                                             
Downloading libqt5network5 - 686 KiB                                                             
libqt5core5a done                                                             
Downloading libqt5gui5 - 2 MiB                                                             
libqt5network5 done                                                             
Downloading libqt5widgets5 - 2 MiB                                                             
libclang1-9 done                                                             
libqt5widgets5 done                                                             
libqt5gui5 done                                                             
Downloading libqt5opengl5 - 163 KiB                                                             
libqt5opengl5 done                                                             
Downloading libqt5printsupport5 - 219 KiB                                                             
libqt5printsupport5 done                                                             
Downloading libqt5sql5 - 148 KiB                                                             
Downloading libqt5sql5-mysql - 76 KiB                                                             
Downloading libqt5sql5-sqlite - 76 KiB                                                             
libqt5sql5-mysql done                                                             
Downloading libqt5test5 - 158 KiB                                                             
libqt5sql5-sqlite done                                                             
libqt5sql5 done                                                             
Downloading libqt5xml5 - 133 KiB                                                             
Downloading libumfpack5 - 239 KiB                                                             
libqt5xml5 done                                                             
libqt5test5 done                                                             
Downloading libxvmc1 - 24 KiB                                                             
Downloading lynx-common - 1 MiB                                                             
libxvmc1 done                                                             
Downloading lynx - 630 KiB                                                             
libumfpack5 done                                                             
Downloading nbdkit - 395 KiB                                                             
nbdkit done                                                             
Downloading python3-louis - 25 KiB                                                             
python3-louis done                                                             
Downloading qt5-gtk-platformtheme - 151 KiB                                                             
lynx done                                                             
libllvm9 done                                                             
Downloading usb.ids - 171 KiB                                                             
qt5-gtk-platformtheme done                                                             
usb.ids done                                                             
lynx-common done                                                             
libllvm9 done                                                             
Downloading x11-apps - 646 KiB                                                             
Downloading x11-session-utils - 70 KiB                                                             
Downloading x11-utils - 197 KiB                                                             
x11-session-utils done                                                             
x11-utils done                                                             
x11-apps done                                                             
Downloading x11-xkb-utils - 159 KiB                                                             
x11-xkb-utils done                                                             
Downloading xkb-data - 639 KiB                                                             
Downloading xserver-common - 2 MiB                                                             
Downloading xserver-xephyr - 2 MiB                                                             
Downloading xserver-xorg-legacy - 2 MiB                                                             
Downloading xserver-xorg-core - 3 MiB                                                             
xkb-data done                                                             
Downloading xwayland - 2 MiB                                                             
xserver-common done                                                             
xserver-xorg-legacy done                                                             
xserver-xorg-core done                                                             
xserver-xephyr done                                                             
xwayland done                                                             
 66 /  66 items: [##############################] 100.0% of 69 MiB
Downloaded data to /tmp/upgrade.zip
12:25 ♒ ॐ  ☺ 😄    
rrs@priyasi:~$ sudo apt-offline install /tmp/upgrade.zip 
Proceeding with installation
libncurses6_6.2-1_amd64.deb file synced.
libncurses6_6.2-1_i386.deb file synced.
libtinfo6_6.2-1_i386.deb file synced.
libtinfo6_6.2-1_amd64.deb file synced.
libncurses-dev_6.2-1_amd64.deb file synced.
libncursesw6_6.2-1_amd64.deb file synced.
ncurses-bin_6.2-1_amd64.deb file synced.
ncurses-base_6.2-1_all.deb file synced.
libcrypt-dev_1%3a4.4.15-1_amd64.deb file synced.
libcrypt1_1%3a4.4.15-1_i386.deb file synced.
libcrypt1_1%3a4.4.15-1_amd64.deb file synced.
libdico2_2.9-2+b2_amd64.deb file synced.
dicod_2.9-2+b2_amd64.deb file synced.
libcupsfilters1_1.27.2-1_amd64.deb file synced.
cups-browsed_1.27.2-1_amd64.deb file synced.
ncurses-term_6.2-1_all.deb file synced.
libfontembed1_1.27.2-1_amd64.deb file synced.
cups-filters-core-drivers_1.27.2-1_amd64.deb file synced.
coinor-libcbc3_2.10.4+repack1-1_amd64.deb file synced.
dh-make_2.202001_all.deb file synced.
libsuitesparseconfig5_1%3a5.7.1+dfsg-2_amd64.deb file synced.
libamd2_1%3a5.7.1+dfsg-2_amd64.deb file synced.
cups-filters_1.27.2-1_amd64.deb file synced.
libcamd2_1%3a5.7.1+dfsg-2_amd64.deb file synced.
libccolamd2_1%3a5.7.1+dfsg-2_amd64.deb file synced.
libcolamd2_1%3a5.7.1+dfsg-2_amd64.deb file synced.
libcholmod3_1%3a5.7.1+dfsg-2_amd64.deb file synced.
liblouis20_3.13.0-1_amd64.deb file synced.
liblouisutdml-data_2.8.0-4_all.deb file synced.
liblouisutdml9_2.8.0-4_amd64.deb file synced.
liblouisutdml-bin_2.8.0-4_amd64.deb file synced.
liblouis-data_3.13.0-1_all.deb file synced.
libqt5concurrent5_5.12.5+dfsg-9_amd64.deb file synced.
libqt5dbus5_5.12.5+dfsg-9_amd64.deb file synced.
libqt5core5a_5.12.5+dfsg-9_amd64.deb file synced.
libqt5network5_5.12.5+dfsg-9_amd64.deb file synced.
libclang1-9_1%3a9.0.1-8+b1_amd64.deb file synced.
libqt5widgets5_5.12.5+dfsg-9_amd64.deb file synced.
libqt5gui5_5.12.5+dfsg-9_amd64.deb file synced.
libqt5opengl5_5.12.5+dfsg-9_amd64.deb file synced.
libqt5printsupport5_5.12.5+dfsg-9_amd64.deb file synced.
libqt5sql5-mysql_5.12.5+dfsg-9_amd64.deb file synced.
libqt5sql5-sqlite_5.12.5+dfsg-9_amd64.deb file synced.
libqt5sql5_5.12.5+dfsg-9_amd64.deb file synced.
libqt5xml5_5.12.5+dfsg-9_amd64.deb file synced.
libqt5test5_5.12.5+dfsg-9_amd64.deb file synced.
libxvmc1_2%3a1.0.12-2_amd64.deb file synced.
libumfpack5_1%3a5.7.1+dfsg-2_amd64.deb file synced.
nbdkit_1.18.0-1+b1_amd64.deb file synced.
python3-louis_3.13.0-1_all.deb file synced.
lynx_2.9.0dev.5-1_amd64.deb file synced.
libllvm9_1%3a9.0.1-8+b1_amd64.deb file synced.
qt5-gtk-platformtheme_5.12.5+dfsg-9_amd64.deb file synced.
usb.ids_2020.02.28-1_all.deb file synced.
lynx-common_2.9.0dev.5-1_all.deb file synced.
libllvm9_1%3a9.0.1-8+b1_i386.deb file synced.
x11-session-utils_7.7+4_amd64.deb file synced.
x11-utils_7.7+5_amd64.deb file synced.
x11-apps_7.7+8_amd64.deb file synced.
x11-xkb-utils_7.7+5_amd64.deb file synced.
xkb-data_2.29-2_all.deb file synced.
xserver-common_2%3a1.20.7-4_all.deb file synced.
xserver-xorg-legacy_2%3a1.20.7-4_amd64.deb file synced.
xserver-xorg-core_2%3a1.20.7-4_amd64.deb file synced.
xserver-xephyr_2%3a1.20.7-4_amd64.deb file synced.
xwayland_2%3a1.20.7-4_amd64.deb file synced.
12:25 ♒ ॐ  ☺ 😄    
rrs@priyasi:~$ sudo apt upgrade
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following packages will be upgraded:
  coinor-libcbc3 cups-browsed cups-filters cups-filters-core-drivers dh-make dicod libamd2 libcamd2 libccolamd2 libcholmod3 libclang1-9
  libcolamd2 libcrypt-dev libcrypt1 libcrypt1:i386 libcupsfilters1 libdico2 libfontembed1 libllvm9 libllvm9:i386 liblouis-data liblouis20
  liblouisutdml-bin liblouisutdml-data liblouisutdml9 libncurses-dev libncurses6 libncurses6:i386 libncursesw6 libqt5concurrent5 libqt5core5a
  libqt5dbus5 libqt5gui5 libqt5network5 libqt5opengl5 libqt5printsupport5 libqt5sql5 libqt5sql5-mysql libqt5sql5-sqlite libqt5test5
  libqt5widgets5 libqt5xml5 libsuitesparseconfig5 libtinfo6 libtinfo6:i386 libumfpack5 libxvmc1 lynx lynx-common nbdkit ncurses-base ncurses-bin
  ncurses-term python3-louis qt5-gtk-platformtheme usb.ids x11-apps x11-session-utils x11-utils x11-xkb-utils xkb-data xserver-common
  xserver-xephyr xserver-xorg-core xserver-xorg-legacy xwayland
66 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/72.6 MB of archives.
After this operation, 287 kB of additional disk space will be used.
Do you want to continue? [Y/n] 
```

**Comment by dandelionred** [comment] 2020-03-05 16:12
@rickysarraf

Ubuntu 18.04 ships with 1.8.1.

I tried installing apt-offline in debian 10 from backports, it has 1.8.2 there. It works OK, but there is a problem with the package: there is no dependency on `python3-apt`. I created a pull request on that.

As for 18.04, I installed there a deb downloaded from debian 10 backports and it worked fine (after installing python3-apt).

**Comment by rickysarraf** [comment] 2020-06-23 15:54
Great Thanks. The dependency has been set proper on `python3-apt` now. Closing this bug report.

**Closed by rickysarraf** 2020-06-23 15:54 UTC
Labels: Need Info
