### ISSUE TITLE
ValueError: too many values to unpack

### ISSUE THREAD

**Issue by viral32111** [rickysarraf/apt-offline#199] opened 2022-10-13 10:49 UTC
Hey, I am getting the following error after attempting to run `sudo apt-offline get --bundle bundle.zip apt-offline.sig` on the *online* system:

```
Fetching APT Data

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apt_offline_core/AptOfflineCoreLib.py", line 864, in stripper
    url, localFile, size, checksum = item.split(' ')
ValueError: too many values to unpack (expected 4)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/apt-offline", line 28, in <module>
    main()
  File "/usr/lib/python3/dist-packages/apt_offline_core/AptOfflineCoreLib.py", line 2503, in main
    args.func(args)
  File "/usr/lib/python3/dist-packages/apt_offline_core/AptOfflineCoreLib.py", line 1253, in fetcher
    (ItemURL, ItemFile, ItemSize, ItemChecksum) = stripper(item)
  File "/usr/lib/python3/dist-packages/apt_offline_core/AptOfflineCoreLib.py", line 868, in stripper
    url, localFile, size = item.split(' ')
ValueError: too many values to unpack (expected 3)
```

The `apt-offline.sig` was generated on the *offline* system using `sudo apt-offline set --upgrade apt-offline.sig`.

I'm running Ubuntu 22.04.1 on both systems, and using version `1.8.5` of this package.

**Comment by jwmynhier** [comment] 2022-10-14 12:49
This appears to be caused by this Ubuntu bug: https://bugs.launchpad.net/ubuntu/+source/ubuntu-advantage-tools/+bug/1992026

I was able to work around it by following the recommendation to remove `/etc/apt/apt.conf.d/20apt-esm-hook.conf` on my online machine.

**Comment by viral32111** [comment] 2022-10-16 13:55
That seems to be right as I've just inspected the contents of the `apt-offline.sig` file and it indeed contains a message about Ubuntu Pro:
```
Try Ubuntu Pro beta with a free personal subscription on up to 5 machines.
Learn more at https://ubuntu.com/pro
```

Removing that file does indeed stop this message from being written to the file, thanks!

**Comment by kyp44** [comment] 2022-10-27 15:51
Fixed this and created a [pull request](https://github.com/rickysarraf/apt-offline/pull/203).

**Comment by rickysarraf** [comment] 2023-03-02 13:42
@kyp44 I see that you closed the PR. Is this still a valid issue ? Otherwise, please close this issue.

We did have another similar issue originating from Ubuntu, where the `apt` output was appended with extra text garbage. I believe that was fixed in one of the previous releases.

**Closed** 2023-03-02 14:22 UTC

**Comment by kyp44** [comment] 2023-03-02 15:31
I believe this was actually fixed in `apt` itself, in that they no longer print the offending message when you run it in silent mode like `apt-offline` does. Like somebody on that development realized, "hey we definitely shouldn't print this message if we're in silent mode".

**Comment by rickysarraf** [comment] 2023-03-02 15:46
> I believe this was actually fixed in `apt` itself, in that they no longer print the offending message when you run it in silent mode like `apt-offline` does. Like somebody on that development realized, "hey we definitely shouldn't print this message if we're in silent mode".

Thanks. I still adapted your proposed change because we needed more checks in place for the generated signature file; given that `apt-offline` caters to many Debian derivatives too.

Similar breakages in the past.

* https://github.com/rickysarraf/apt-offline/issues/190
* https://github.com/rickysarraf/apt-offline/issues/163
* https://github.com/rickysarraf/apt-offline/issues/147 (reported by you @kyp44 )
